/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadDataRouteImport } from './routes/uploadData'
import { Route as OriginDataCategoryRouteImport } from './routes/originDataCategory'
import { Route as OccupationDataCategoryRouteImport } from './routes/occupationDataCategory'
import { Route as ManageDataRouteImport } from './routes/manageData'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as GenderDataCategoryRouteImport } from './routes/genderDataCategory'
import { Route as EducationDataCategoryRouteImport } from './routes/educationDataCategory'
import { Route as DestinationDataCategoryRouteImport } from './routes/destinationDataCategory'
import { Route as CivilstatusDataCategoryRouteImport } from './routes/civilstatusDataCategory'
import { Route as AgeCategoryRouteImport } from './routes/ageCategory'
import { Route as IndexRouteImport } from './routes/index'

const UploadDataRoute = UploadDataRouteImport.update({
  id: '/uploadData',
  path: '/uploadData',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginDataCategoryRoute = OriginDataCategoryRouteImport.update({
  id: '/originDataCategory',
  path: '/originDataCategory',
  getParentRoute: () => rootRouteImport,
} as any)
const OccupationDataCategoryRoute = OccupationDataCategoryRouteImport.update({
  id: '/occupationDataCategory',
  path: '/occupationDataCategory',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDataRoute = ManageDataRouteImport.update({
  id: '/manageData',
  path: '/manageData',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const GenderDataCategoryRoute = GenderDataCategoryRouteImport.update({
  id: '/genderDataCategory',
  path: '/genderDataCategory',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationDataCategoryRoute = EducationDataCategoryRouteImport.update({
  id: '/educationDataCategory',
  path: '/educationDataCategory',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationDataCategoryRoute = DestinationDataCategoryRouteImport.update({
  id: '/destinationDataCategory',
  path: '/destinationDataCategory',
  getParentRoute: () => rootRouteImport,
} as any)
const CivilstatusDataCategoryRoute = CivilstatusDataCategoryRouteImport.update({
  id: '/civilstatusDataCategory',
  path: '/civilstatusDataCategory',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeCategoryRoute = AgeCategoryRouteImport.update({
  id: '/ageCategory',
  path: '/ageCategory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ageCategory': typeof AgeCategoryRoute
  '/civilstatusDataCategory': typeof CivilstatusDataCategoryRoute
  '/destinationDataCategory': typeof DestinationDataCategoryRoute
  '/educationDataCategory': typeof EducationDataCategoryRoute
  '/genderDataCategory': typeof GenderDataCategoryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/manageData': typeof ManageDataRoute
  '/occupationDataCategory': typeof OccupationDataCategoryRoute
  '/originDataCategory': typeof OriginDataCategoryRoute
  '/uploadData': typeof UploadDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ageCategory': typeof AgeCategoryRoute
  '/civilstatusDataCategory': typeof CivilstatusDataCategoryRoute
  '/destinationDataCategory': typeof DestinationDataCategoryRoute
  '/educationDataCategory': typeof EducationDataCategoryRoute
  '/genderDataCategory': typeof GenderDataCategoryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/manageData': typeof ManageDataRoute
  '/occupationDataCategory': typeof OccupationDataCategoryRoute
  '/originDataCategory': typeof OriginDataCategoryRoute
  '/uploadData': typeof UploadDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ageCategory': typeof AgeCategoryRoute
  '/civilstatusDataCategory': typeof CivilstatusDataCategoryRoute
  '/destinationDataCategory': typeof DestinationDataCategoryRoute
  '/educationDataCategory': typeof EducationDataCategoryRoute
  '/genderDataCategory': typeof GenderDataCategoryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/manageData': typeof ManageDataRoute
  '/occupationDataCategory': typeof OccupationDataCategoryRoute
  '/originDataCategory': typeof OriginDataCategoryRoute
  '/uploadData': typeof UploadDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ageCategory'
    | '/civilstatusDataCategory'
    | '/destinationDataCategory'
    | '/educationDataCategory'
    | '/genderDataCategory'
    | '/landing'
    | '/login'
    | '/manageData'
    | '/occupationDataCategory'
    | '/originDataCategory'
    | '/uploadData'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ageCategory'
    | '/civilstatusDataCategory'
    | '/destinationDataCategory'
    | '/educationDataCategory'
    | '/genderDataCategory'
    | '/landing'
    | '/login'
    | '/manageData'
    | '/occupationDataCategory'
    | '/originDataCategory'
    | '/uploadData'
  id:
    | '__root__'
    | '/'
    | '/ageCategory'
    | '/civilstatusDataCategory'
    | '/destinationDataCategory'
    | '/educationDataCategory'
    | '/genderDataCategory'
    | '/landing'
    | '/login'
    | '/manageData'
    | '/occupationDataCategory'
    | '/originDataCategory'
    | '/uploadData'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgeCategoryRoute: typeof AgeCategoryRoute
  CivilstatusDataCategoryRoute: typeof CivilstatusDataCategoryRoute
  DestinationDataCategoryRoute: typeof DestinationDataCategoryRoute
  EducationDataCategoryRoute: typeof EducationDataCategoryRoute
  GenderDataCategoryRoute: typeof GenderDataCategoryRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ManageDataRoute: typeof ManageDataRoute
  OccupationDataCategoryRoute: typeof OccupationDataCategoryRoute
  OriginDataCategoryRoute: typeof OriginDataCategoryRoute
  UploadDataRoute: typeof UploadDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploadData': {
      id: '/uploadData'
      path: '/uploadData'
      fullPath: '/uploadData'
      preLoaderRoute: typeof UploadDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/originDataCategory': {
      id: '/originDataCategory'
      path: '/originDataCategory'
      fullPath: '/originDataCategory'
      preLoaderRoute: typeof OriginDataCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occupationDataCategory': {
      id: '/occupationDataCategory'
      path: '/occupationDataCategory'
      fullPath: '/occupationDataCategory'
      preLoaderRoute: typeof OccupationDataCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manageData': {
      id: '/manageData'
      path: '/manageData'
      fullPath: '/manageData'
      preLoaderRoute: typeof ManageDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genderDataCategory': {
      id: '/genderDataCategory'
      path: '/genderDataCategory'
      fullPath: '/genderDataCategory'
      preLoaderRoute: typeof GenderDataCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educationDataCategory': {
      id: '/educationDataCategory'
      path: '/educationDataCategory'
      fullPath: '/educationDataCategory'
      preLoaderRoute: typeof EducationDataCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinationDataCategory': {
      id: '/destinationDataCategory'
      path: '/destinationDataCategory'
      fullPath: '/destinationDataCategory'
      preLoaderRoute: typeof DestinationDataCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/civilstatusDataCategory': {
      id: '/civilstatusDataCategory'
      path: '/civilstatusDataCategory'
      fullPath: '/civilstatusDataCategory'
      preLoaderRoute: typeof CivilstatusDataCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ageCategory': {
      id: '/ageCategory'
      path: '/ageCategory'
      fullPath: '/ageCategory'
      preLoaderRoute: typeof AgeCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgeCategoryRoute: AgeCategoryRoute,
  CivilstatusDataCategoryRoute: CivilstatusDataCategoryRoute,
  DestinationDataCategoryRoute: DestinationDataCategoryRoute,
  EducationDataCategoryRoute: EducationDataCategoryRoute,
  GenderDataCategoryRoute: GenderDataCategoryRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ManageDataRoute: ManageDataRoute,
  OccupationDataCategoryRoute: OccupationDataCategoryRoute,
  OriginDataCategoryRoute: OriginDataCategoryRoute,
  UploadDataRoute: UploadDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
